#!/bin/bash
cat > /home/ubuntu/setup.sh << __EOF__
#!/bin/bash

##  Configure OS ##############################################################
echo
echo "Disabling swap..."
sudo swapoff -a
echo
echo "Increasing vm.max_map_count..."
sudo sysctl -w vm.max_map_count=262144

mkdir /home/ubuntu/elastic
mkdir /home/ubuntu/data
cd /home/ubuntu/elastic

##  Install Elasticsearch, Kibana, and Filebeat ###############################
echo
echo "Installing Elasticsearch, Kibana, and Filebeat, Metricbeat, Auditbeat ..."

echo "Elasticsearch"
wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.4.1-linux-x86_64.tar.gz
tar -xzf elasticsearch-7.4.1-linux-x86_64.tar.gz

echo "Kibana"
wget https://artifacts.elastic.co/downloads/kibana/kibana-7.4.1-linux-x86_64.tar.gz
tar -xzf kibana-7.4.1-linux-x86_64.tar.gz

echo "Filebeat"
curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.4.1-linux-x86_64.tar.gz
tar xzvf filebeat-7.4.1-linux-x86_64.tar.gz

echo "Metricbeat"
curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.4.1-linux-x86_64.tar.gz
tar xzvf metricbeat-7.4.1-linux-x86_64.tar.gz

echo "Auditbeat"
curl -L -O https://artifacts.elastic.co/downloads/beats/auditbeat/auditbeat-7.4.1-linux-x86_64.tar.gz
tar xzvf auditbeat-7.4.1-linux-x86_64.tar.gz

##  Configure Elasticsearch and Kibana ########################################
echo
echo "Configuring Elasticsearch and Kibana..."
sed -i "s/^#\?cluster\.name:.*/cluster.name: \"elasticsearch-workshop\"/" /home/ubuntu/elastic/elasticsearch-7.4.1/config/elasticsearch.yml
sed -i "s/^#\?node\.name:.*/node.name: \"node-1\"/" /home/ubuntu/elastic/elasticsearch-7.4.1/config/elasticsearch.yml
sed -i "s/^#\?discovery\.seed_hosts:.*/discovery.seed_hosts: \[\"127.0.0.1\"\]/" /home/ubuntu/elastic/elasticsearch-7.4.1/config/elasticsearch.yml
echo "discovery.type: single-node" >> /home/ubuntu/elastic/elasticsearch-7.4.1/config/elasticsearch.yml
echo "#xpack.security.enabled: true" >> /home/ubuntu/elastic/elasticsearch-7.4.1/config/elasticsearch.yml                                               

echo "Kibana"
sed -i "s/^#\?server\.host:.*/server.host: \"0.0.0.0\"/" /home/ubuntu/elastic/kibana-7.4.1-linux-x86_64/config/kibana.yml
sed -i "s/^#\?elasticsearch\.hosts:.*/elasticsearch.hosts: \[\"http:\/\/127.0.0.1:9200\"\]/" /home/ubuntu/elastic/kibana-7.4.1-linux-x86_64/config/kibana.yml

##  Configure Filebeat ########################################################
echo
echo "Configuring Filebeat..."
sed -i "s/^  \?hosts:.*/  hosts: [\"127.0.0.1\"]/" /home/ubuntu/elastic/filebeat-7.4.1-linux-x86_64/filebeat.yml
sed -i "s/^#\?setup.dashboards.enabled:.*/setup.dashboards.enabled: true/" /home/ubuntu/elastic/filebeat-7.4.1-linux-x86_64/filebeat.yml

##  Configure Metricbeat ########################################################
echo
echo "Configuring Metricbeat..."
sed -i "s/^  \?hosts:.*/  hosts: [\"127.0.0.1\"]/" /home/ubuntu/elastic/metricbeat-7.4.1-linux-x86_64/metricbeat.yml
sed -i "s/^#\?setup.dashboards.enabled:.*/setup.dashboards.enabled: true/" /home/ubuntu/elastic/metricbeat-7.4.1-linux-x86_64/metricbeat.yml

##  Configure Auditbeat ########################################################
echo
echo "Configuring Auditbeat..."
sed -i "s/^  \?hosts:.*/  hosts: [\"127.0.0.1\"]/" /home/ubuntu/elastic/auditbeat-7.4.1-linux-x86_64/auditbeat.yml
sed -i "s/^#\?setup.dashboards.enabled:.*/setup.dashboards.enabled: true/" /home/ubuntu/elastic/auditbeat-7.4.1-linux-x86_64/auditbeat.yml

##  Download Data ############################################################# 
echo
echo "Downloading data..."
sudo apt-get -y install unzip
wget https://storage.googleapis.com/elasticsearch-sizing-workshop/data/nginx.zip -O /home/ubuntu/data/nginx.zip
unzip -j /home/ubuntu/data/nginx.zip nginx.log -d /home/ubuntu/data/
__EOF__

chown ubuntu:ubuntu /home/ubuntu/setup.sh
chmod u+x /home/ubuntu/setup.sh

su ubuntu -c  "/home/ubuntu/setup.sh"

exit
